//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperFastBlogAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_article
    {
        public tbl_article()
        {
            this.tbl_contact = new HashSet<tbl_contact>();
        }
    
        public int ID { get; set; }
        public string Topic { get; set; }
        public string Heading { get; set; }
        public string Content { get; set; }
        public byte[] Image { get; set; }
        public int PostedUserID { get; set; }
        public System.DateTime DatePosted { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
        public virtual ICollection<tbl_contact> tbl_contact { get; set; }
    }
}
